### ISSUE TITLE
Adjusting boxplot placement for raw data plots

### ISSUE THREAD

**Issue by ethai98** [xuyiqing/interflex#15]
Hi! I recently discovered this package and it's a really great tool. A quick question I have is how to adjust the placement of the boxplot when plotting the raw data. I see in the paper that the boxplots are sometimes placed near the top of the plots; however, I can't find the options within interflex() to adjust this. My data currently is quite crowded near 0 (see attached), and the boxplot being fixed there doesn't help with readability. Would appreciate your help on moving the boxplot to be near the top of the plots, thanks!

Also, it seems that ylim() option doesn't work when the estimator is "raw."

![image](https://github.com/xuyiqing/interflex/assets/71897701/fd062c65-ba35-4b96-b79b-de364568c1b4)

**Comment by xuyiqing** [comment]
Thank you! We'll try to incorporate your suggestions if they're feasible. Stay tuned.

**Comment by TianzhuQin** [comment]
@ethai98 Hi Ethai, please use the dml branch to use the box.pos (input "up" or "down"), xlim or ylim. I hope this can meet your needs and it will be merged to main branch soon.

`install_github("xuyiqing/interflex", branch = "dml")`

`interflex(estimator = "raw",Y = "Y", D = "D", X = "X", data = s1,
          weights = NULL, Ylabel = "Outcome",
          Dlabel = "Treatment", Xlabel="Moderator",
          main = "Raw Plot", cex.main = 1.2, box.pos="up", xlim=c(2,4))`
