### ISSUE TITLE
Adding analytical SEs to reduce memory requirements

### ISSUE THREAD

**Issue by JonathanDavidKay** [xuyiqing/interflex#16]
I'm attempting to use interflex with a very large dataset (150 million observations, 18 GB) and running into memory limitations (despite using some high-resource virtual computing - 200 GB of RAM in my last attempt). As one step toward accommodating this sort of usecase, would it be possible to add an option to calculate analytical SEs rather than bootstrapping them? Or are there any other modifications you could make to the backend to optimize memory usage (possibly akin to the mem.clean option in feols(), which attempts to remove intermediary objects as much as possible and calls gc() after each major C++ section in the code)?

Thank you very much!

**Comment by xuyiqing** [comment]
Thank you, Jonathan. We'll get to it as soon as we can.

**Comment by TianzhuQin** [comment]
@JonathanDavidKay Hi Jonathan, please see dml branch. By setting vartype to "delta", you can get the SEs with no need of bootstrapping. I hope this meets your requirement.

`install_github("xuyiqing/interflex", branch = "dml")`

`out_test_delta <- interflex(Y = "Y", D = "D", X = "X", Z = c("Z1", "Z2"), data = s7, estimator = "kernel", bw=0.5285, parallel = TRUE, cores = 4, vartype="delta")`

**Comment by JonathanDavidKay** [comment]
Thanks so much for implementing this!

For whatever reason, it still seems to be consuming quite a lot of memory - approximately twice as much as the equivalent feols(). For context, I'm running (with generalized variable names):

interflex(data = df, Y = "y_var", D = "treat", X = "x_var", Z = "z_var", FE = c("fe1", "fe2", "fe3"), 
                estimator = "binning", 
                na.rm = TRUE, vartype = "delta")

Perhaps the size of my data (and the fact I'm trying to include three different fixed effects) is simply not a good fit for the function.

Anyways, thanks for trying - I'll experiment with subsetting my data to see if I can reduce overall demands.
